# BEGIN_KITTY_FONTS
font_family      family="SauceCodePro Nerd Font Mono"
font_size        13.0
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# BEGIN_KITTY_THEME
# Kanagawa
include current-theme.conf
# END_KITTY_THEME

# Nicer macOS feel
macos_option_as_alt left
window_padding_width 4
hide_window_decorations no

# Cursor
cursor_shape beam

# Scrollback
scrollback_lines 10000

# URL handling - cmd+click opens URLs
open_url_with default
