# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME=lee

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(docker git history npm node z zsh-completions)

source $ZSH/oh-my-zsh.sh
# initialize zsh-completions
autoload -U compinit && compinit

export GOPATH=~/projects/go
PATH=/usr/local/bin:$PATH
PATH=/usr/local/sbin:$PATH
PATH=$PATH:/bin:/~/bin:/sbin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.cask/bin:$GOPATH/bin
PATH=$HOME/.local/bin:$HOME/.cabal/bin:$PATH

# Customize to your needs...
ulimit -n 10000

alias 'cd..'="cd .."
alias c=clear

if [ -x $(brew --prefix)/bin/nvim ]; then
  alias {v,vi,vim}=nvim
  alias ovim=$(brew --prefix)/bin/vim
fi

alias t=tmux
alias ta='tmux attach'
alias tl='tmux list-sessions'
alias td='tmux detach'

export EDITOR=vim

# Add base16 support
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

export LSCOLORS="Exfxcxdxbxegedabagacad"

local ret_status="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ %s)"
PROMPT='${ret_status}%{$fg_bold[green]%}%p %{$fg[white]%}%c%{$fg_bold[white]%}$(git_prompt_info)%{$fg_bold[white]%} % %{$reset_color%}'

ZSH_THEME_GIT_PROMPT_PREFIX="(%{$fg[blue]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[white]%}) %{$fg[red]%}✗%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[white]%})"

MANPATH=$(brew --prefix)/share/man:
INFOPATH=$(brew --prefix)/share/info:

# Initialise fzf fuzzyfinder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Initialise opam
source /Users/leebannard/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
eval $(opam config env)

export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export ERL_AFLAGS="-kernel shell_history enabled"

# Initialise asdf
source /usr/local/opt/asdf/asdf.sh

export PATH
